name: Test-Linter

on: push    

jobs:
  super-lint:
   name: Lint code base
   runs-on: ubuntu-20.04
   steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        continue-on-error: true
        uses: github/super-linter@v4
        env:
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# #This is due to alot of mail sending! :D